### ISSUE TITLE
Build Azure support

### ISSUE THREAD

**Issue by bendehaan** [OWASP/wrongsecrets-ctf-party#156]

**Comment by osamamagdy** [comment]
Hello @commjoen, I am Osama Magdy and I've been working as a DevOps Engineer for 2 years I've been working with Azure for one year and I have a particular interest in this idea for GSoC 23, I want to learn more about the wrong secrets infrastructure by adding Azure support. It also will help me to gain more experience in Azure and increase my skills in general. I wonder about some more details. How to start getting to know the code base, Good First issue, or Are there any qualification tasks I can start with? And what is the main communication medium so I can introduce myself more to the community 😀. I found the Slack channel on the website but I think something is going wrong and I can not log in there.
Although I prefer to work on this as it's more challenging, I also have an interest in these two ideas https://github.com/OWASP/wrongsecrets-ctf-party/issues/84 and https://github.com/OWASP/wrongsecrets-ctf-party/issues/86. I will be commenting there and waiting for your response

**Comment by commjoen** [comment]
Hi @osamamagdy , let's start with https://github.com/OWASP/wrongsecrets-ctf-party/issues/86 ;) first :D . Welcome aboard!

**Comment by osamamagdy** [comment]
Hi @commjoen, thanks for letting me know but I wonder if #86 is more important for wrongsecrets than here?
