### ISSUE TITLE
make cleaner delete full namespace instead of deployment

### ISSUE THREAD

**Issue by commjoen** [OWASP/wrongsecrets-ctf-party#54]
make the cleaner delete the full namespace instead of the deployment

**Comment by osamamagdy** [comment]
Hello @commjoen, I am working on this but I wonder if the deployment deletion is working in the first place? I tried to play a little with it and the deployment had the last request annotation for 2 days but the logs of the cleanup pod were mentioning less than 1s. I also modified the grace period to be `2m` to see the deletion process being executed but got no luck. 
![image](https://user-images.githubusercontent.com/59124937/219225941-62ee20c9-62b8-4410-89d1-af06453cdde7.png)

**Comment by osamamagdy** [comment]
Can you point to what I missed?

**Comment by commjoen** [comment]
The cleaner it’s code needs to be adjusted. It does not cleanup anything yet.
So first it needs to be changed in terms of code (e.g. make it enumerate namespaces and  make it cleanup older namespaces that start with ‘t-‘ but only if we set it to delete instead of just to enumerate/report)

**Comment by osamamagdy** [comment]
>  but only if we set it to delete instead of just to enumerate/report in the helm chart)

Do you mean I also should add an enabling condition to switch between enumeration and deletion?

**Comment by commjoen** [comment]
Yes sir!

**Comment by osamamagdy** [comment]
Great, will do it with ENV and get back to you with another question when needed 😄

**Comment by osamamagdy** [comment]
Hello @commjoen, the approach I'm following now is to list all namespaces, and for each namespace check if there is at least one active deployment ( time of inactivity is less than the grace period), and if not, delete this namespace completely. 
My question is: In this case, if there is a namespace with multiple deployments but only one of them is active, the cleaner will neither delete the namespace not any of the inactive deployments

**Comment by commjoen** [comment]
that is indeed correcrt: because people might be busy with just the webtop or the wrongsecrets instance, but not both...

**Comment by osamamagdy** [comment]
Thanks for the clarification @commjoen, I created a PR to close this issue and waiting for your review 😀😀
