### ISSUE TITLE
Move EKS autoscaling to TF

### ISSUE THREAD

**Issue by commjoen** [OWASP/wrongsecrets-ctf-party#84]
Currently autoscaling happens from a set of scripts and files, while there is also https://github.com/terraform-aws-modules/terraform-aws-eks/blob/4898bf326d7019fdd9cc33b533a226d6ef3a0f52/examples/irsa_autoscale_refresh/charts.tf#L9-L78 . Let's migrate to it!

**Comment by osamamagdy** [comment]
Hello @commjoen, I am Osama Magdy and I've been working as a DevOps Engineer for 2 years and worked a lot with Terraform. I have a particular interest in this idea for GSoC 23 and wonder about some more details. How to start getting to know the code base, Good First issue, or Are there any qualification tasks I can start with? And what is the main communication medium so I can introduce myself more to the community 😀
I also have an interest in these two ideas #86 and #156. I will be commenting there and waiting for your response.
