### ISSUE TITLE
Cleanup helm chart

### ISSUE THREAD

**Issue by commjoen** [OWASP/wrongsecrets-ctf-party#86]
- [x] remove everything progress related
- [ ] have all the loadbalancer things in helm:
  - [ ] move all pod related items to config.json & make entries in config-map.yaml linked to values in helm chart for container deployments
  - [ ] check other hardcoded items, move them to deployment.yaml linked to values in helm chart
- [ ] Have all the WrongSecrets things helm: deployment.yaml and values.yaml
- [ ] Have all the webtop things in helm: deployment.yaml and values.yaml
- [ ] Have a proper name for the helm chart
- [ ] Remove whatever is not used in the helm chart
- [ ] Add release-script where containers and helm version are in sync with wrongSecrets (e.g. tag and push)

**Comment by osamamagdy** [comment]
Hello @commjoen, I am Osama Magdy and I've been working as a DevOps Engineer for 2 years I've created a complete Helm chart from scratch for different organizations before (one of them had more than 200 Kubernetes manifests). I have a particular interest in this idea for GSoC 23 and wonder about some more details. How to start getting to know the code base, Good First issue, or Are there any qualification tasks I can start with? And what is the main communication medium so I can introduce myself more to the community 😀. I found the Slack channel on the website but I think something is going wrong and I can not log in there
I also have an interest in these two ideas https://github.com/OWASP/wrongsecrets-ctf-party/issues/84 and https://github.com/OWASP/wrongsecrets-ctf-party/issues/156. I will be commenting there and waiting for your response.

**Comment by commjoen** [comment]
The floor is yours sir :) . Feel free to DM @bendehaan &me for any questions on this ticket if required.

**Comment by osamamagdy** [comment]
Thanks @commjoen, I already introduced myself on slack and am excited to meet you all there 😀. 
I will start asking on slack for better visibility to all org members.

**Comment by osamamagdy** [comment]
After closing #54, I am able to understand the chart clearly now. Will start working on this soon.

**Comment by commjoen** [comment]
I will create and push a new version of your cleaner container this week so it will work without having to build anything
